name: just_transitions
version: 1.0.1
description: A package to make it easy to navigate between routes
  using animations and customizing them with different features.
homepage: https://github.com/DamianAldair/just_transitions
repository: https://github.com/DamianAldair/just_transitions

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
